# Generated by Django 3.1.6 on 2021-02-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='部门编号')),
                ('department_name', models.CharField(max_length=128, unique=True, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='活动编号')),
                ('name', models.CharField(max_length=128, verbose_name='活动名称')),
                ('department_name', models.CharField(max_length=128, verbose_name='主办单位')),
                ('semester', models.CharField(max_length=64, verbose_name='活动时间')),
                ('category', models.CharField(max_length=64, verbose_name='活动类型')),
                ('certify_state', models.CharField(max_length=64, verbose_name='认证状态')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], verbose_name='性别')),
                ('department_name', models.CharField(default=None, max_length=64, verbose_name='学院')),
                ('major_name', models.CharField(default=None, max_length=64, verbose_name='专业')),
                ('grade', models.IntegerField(verbose_name='年级')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='StudentJoinProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='学号')),
                ('student_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('project_id', models.IntegerField(verbose_name='活动编号')),
                ('project_name', models.CharField(max_length=128, verbose_name='活动名称')),
            ],
            options={
                'verbose_name': '学生参与活动信息',
                'verbose_name_plural': '学生参与活动信息',
            },
        ),
    ]
