# Generated by Django 3.1.6 on 2021-02-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentjoinproject',
            old_name='project_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='studentjoinproject',
            old_name='student_id',
            new_name='s_id',
        ),
    ]
