# Generated by Django 3.1.6 on 2021-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210224_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentjoinproject',
            name='p_id',
            field=models.IntegerField(default=None, verbose_name='活动编号'),
        ),
    ]
