# Generated by Django 3.1.6 on 2021-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210224_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='studentjoinproject',
            name='s_id',
            field=models.CharField(max_length=64, verbose_name='学号'),
        ),
    ]
