# Generated by Django 3.1.6 on 2021-03-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210225_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjoinproject',
            name='semester',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='活动时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='活动时间'),
        ),
    ]
