# Generated by Django 3.0.5 on 2021-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210303_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=64, verbose_name='学号')),
                ('org_name', models.CharField(max_length=128, verbose_name='组织名称')),
                ('position', models.CharField(max_length=64, verbose_name='职务')),
                ('start_time', models.DateField(verbose_name='开始日期')),
                ('end_time', models.DateField(verbose_name='结束日期')),
                ('department_name', models.CharField(max_length=128, verbose_name='部门名称')),
                ('certify_state', models.CharField(blank=True, default=None, max_length=64, verbose_name='认证状态')),
            ],
            options={
                'verbose_name': '学生组织活动信息',
                'verbose_name_plural': '学生组织活动信息',
            },
        ),
        migrations.CreateModel(
            name='StudentScholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=64, verbose_name='学号')),
                ('g_time', models.DateField(verbose_name='获奖时间')),
                ('scholar_name', models.CharField(max_length=64, verbose_name='奖学金名称')),
                ('level', models.CharField(max_length=64, verbose_name='奖学金级别')),
                ('certify_state', models.CharField(blank=True, default=None, max_length=64, verbose_name='认证状态')),
            ],
            options={
                'verbose_name': '学生获奖信息',
                'verbose_name_plural': '学生获奖信息',
            },
        ),
    ]
