# Generated by Django 3.0.5 on 2021-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentorganization_studentscholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentorganization',
            name='certify_state',
            field=models.CharField(blank=True, default='未认证', max_length=64, verbose_name='认证状态'),
        ),
    ]
