# Generated by Django 3.0.5 on 2021-03-17 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0008_auto_20210313_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscholar',
            name='certify_state',
            field=models.CharField(blank=True, default='未认证', max_length=64, verbose_name='认证状态'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField(choices=[(0, '统计与信息学院'), (1, '工商管理学院'), (2, '国际经贸学院'), (3, '国际商务外语学院'), (4, '金融管理学院'), (5, '会展与旅游学院'), (6, '法学院'), (7, '贸易谈判学院'), (8, '会计学院')], verbose_name='所在部门')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户补充信息',
                'verbose_name_plural': '用户补充信息',
            },
        ),
    ]
