# Generated by Django 3.0.5 on 2021-03-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210317_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentorganization',
            options={'ordering': ['created_time'], 'verbose_name': '学生组织活动信息', 'verbose_name_plural': '学生组织活动信息'},
        ),
        migrations.AlterModelOptions(
            name='studentscholar',
            options={'ordering': ['created_time'], 'verbose_name': '学生获奖信息', 'verbose_name_plural': '学生获奖信息'},
        ),
    ]
