# Generated by Django 3.0.5 on 2021-03-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210319_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentorganization',
            name='update_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='studentscholar',
            name='update_time',
            field=models.DateTimeField(editable=False, null=True, verbose_name='更新时间'),
        ),
    ]
