# Generated by Django 3.0.5 on 2021-03-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64, verbose_name='学号')),
                ('org_id', models.IntegerField(verbose_name='活动序号')),
                ('admin_id', models.CharField(max_length=64, null=True, verbose_name='教师用户名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(editable=False, null=True, verbose_name='最近更新时间')),
                ('state', models.IntegerField(choices=[(0, '提交'), (1, '完成'), (2, '驳回')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '组织活动流程信息',
                'verbose_name_plural': '组织活动流程信息',
            },
        ),
        migrations.CreateModel(
            name='ScholarProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64, verbose_name='学号')),
                ('scholar_id', models.IntegerField(verbose_name='活动序号')),
                ('admin_id', models.CharField(max_length=64, null=True, verbose_name='教师用户名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(editable=False, null=True, verbose_name='最近更新时间')),
                ('state', models.IntegerField(choices=[(0, '提交'), (1, '完成'), (2, '驳回')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '奖学金流程信息',
                'verbose_name_plural': '奖学金流程信息',
            },
        ),
    ]
