# Generated by Django 3.0.5 on 2021-03-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarprocess',
            name='state',
            field=models.CharField(max_length=64, verbose_name='状态'),
        ),
    ]
