# Generated by Django 3.0.5 on 2021-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20210319_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprocess',
            name='state',
            field=models.CharField(max_length=64, verbose_name='状态'),
        ),
    ]
